// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Chessie.Hopac.Tests")>]
[<assembly: AssemblyProductAttribute("Chessie.Hopac")>]
[<assembly: AssemblyVersionAttribute("0.5.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2018-08-24T11:08:32.1326620-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.5.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.5.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","7c2322a58212e24e77c650ac40abfb0c0da03ed1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Chessie.Hopac.Tests"
    let [<Literal>] AssemblyProduct = "Chessie.Hopac"
    let [<Literal>] AssemblyVersion = "0.5.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2018-08-24T11:08:32.1326620-04:00"
    let [<Literal>] AssemblyFileVersion = "0.5.0"
    let [<Literal>] AssemblyInformationalVersion = "0.5.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "7c2322a58212e24e77c650ac40abfb0c0da03ed1"
