// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Chessie.Hopac")>]
[<assembly: AssemblyProductAttribute("Chessie.Hopac")>]
[<assembly: AssemblyVersionAttribute("0.5.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2019-05-28T10:23:58.1049110-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.5.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.5.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","36a368a164a88d7eddf1fd5de8f656d4279bdfda")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Chessie.Hopac"
    let [<Literal>] AssemblyProduct = "Chessie.Hopac"
    let [<Literal>] AssemblyVersion = "0.5.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2019-05-28T10:23:58.1049110-04:00"
    let [<Literal>] AssemblyFileVersion = "0.5.1"
    let [<Literal>] AssemblyInformationalVersion = "0.5.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "36a368a164a88d7eddf1fd5de8f656d4279bdfda"
