// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Chessie.Hopac")>]
[<assembly: AssemblyProductAttribute("Chessie.Hopac")>]
[<assembly: AssemblyDescriptionAttribute("Railray Oriented Programming with Hopac expressions")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Chessie.Hopac"
    let [<Literal>] AssemblyProduct = "Chessie.Hopac"
    let [<Literal>] AssemblyDescription = "Railray Oriented Programming with Hopac expressions"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
